In [1]:
import numpy as np



In [5]:
# numpy indexing and slicing of vectors

arr=np.arange(11,31)
arr

array([11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27,
       28, 29, 30])

In [6]:
arr[5]

np.int64(16)

In [7]:
arr[1:4]

array([12, 13, 14])

In [8]:
arr[3::2]

array([14, 16, 18, 20, 22, 24, 26, 28, 30])

In [10]:
# numpy indexing and slicing of matrix

arr=np.arange(1,31).reshape(6,5)
arr  # 2d array

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25],
       [26, 27, 28, 29, 30]])

In [11]:
arr[0,0]

np.int64(1)

In [12]:
arr[0,4]

np.int64(5)

In [13]:
arr[1]

array([ 6,  7,  8,  9, 10])

In [14]:
# numpy indexing and slicing of matrix

arr[0:2,1:3]

array([[2, 3],
       [7, 8]])

In [15]:
# boolean indexing

arr=np.arange(11,21)
arr

array([11, 12, 13, 14, 15, 16, 17, 18, 19, 20])

In [16]:
bool_index=arr%2==0
bool_index

array([False,  True, False,  True, False,  True, False,  True, False,
        True])

In [17]:
arr=arr[bool_index]
arr

array([12, 14, 16, 18, 20])