In [2]:
import numpy as np


#Array operations

In [3]:
# arithmatic operations
a1=np.array([1,2,3,4])
a2=np.array([5,6,7,8])


In [4]:
a1

array([1, 2, 3, 4])

In [5]:
a2

array([5, 6, 7, 8])

In [7]:
a1+a2 # size must be same

array([ 6,  8, 10, 12])

In [8]:
a1-a2

array([-4, -4, -4, -4])

In [9]:
a1*a2

array([ 5, 12, 21, 32])

In [10]:
a1/a2

array([0.2       , 0.33333333, 0.42857143, 0.5       ])

In [11]:
a1//a2

array([0, 0, 0, 0])

In [12]:
a1**2

array([ 1,  4,  9, 16])

In [13]:
# broadcasting
l=[10,20,30,40]
arr=np.array(l)

In [14]:
for i in l:
    print(i+10)

20
30
40
50


In [15]:
# by using numpy 
arr+10

array([20, 30, 40, 50])

In [17]:
arr2=np.arange(1,26).reshape(5,5)
arr2+12

array([[13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22],
       [23, 24, 25, 26, 27],
       [28, 29, 30, 31, 32],
       [33, 34, 35, 36, 37]])

In [19]:
# deep and shallow copy

slice=arr2[:5]
slice=slice*10
slice

array([[ 10,  20,  30,  40,  50],
       [ 60,  70,  80,  90, 100],
       [110, 120, 130, 140, 150],
       [160, 170, 180, 190, 200],
       [210, 220, 230, 240, 250]])

In [20]:
# agr main array mein change => deep copy 
# and agr main array mein chnages nhi hote hai => shallow copy

In [21]:
arr2
b=arr2

In [22]:
b[0]=99
b

array([[99, 99, 99, 99, 99],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]])

In [24]:
# marix operations

mat1=np.arange(1,5).reshape(2,2)
mat2=np.arange(5,9).reshape(2,2)
mat1

array([[1, 2],
       [3, 4]])

In [25]:
mat2

array([[5, 6],
       [7, 8]])

In [27]:
mat1 @ mat2 # matrix multiplication or dot product

array([[19, 22],
       [43, 50]])

In [28]:
np.dot(mat1,mat2)

array([[19, 22],
       [43, 50]])

In [29]:
mat1.T

array([[1, 3],
       [2, 4]])

In [32]:
# advance array manipulation

# 1. stacking array

a=np.array([1,2,3,4])
b=np.array([5,6,7,8])

np.vstack((a,b))
# one bracket => only takes one argument


array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [33]:
np.hstack((a,b))

array([1, 2, 3, 4, 5, 6, 7, 8])

In [35]:
np.column_stack((a,b))

array([[1, 5],
       [2, 6],
       [3, 7],
       [4, 8]])

In [36]:
# 2. splitting array

c=np.arange(16).reshape(4,4)
c

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [38]:
np.hsplit(c,2)

[array([[ 0,  1],
        [ 4,  5],
        [ 8,  9],
        [12, 13]]),
 array([[ 2,  3],
        [ 6,  7],
        [10, 11],
        [14, 15]])]

In [39]:
np.vsplit(c,2)

[array([[0, 1, 2, 3],
        [4, 5, 6, 7]]),
 array([[ 8,  9, 10, 11],
        [12, 13, 14, 15]])]