In [1]:
import numpy as np


In [2]:
# python => no arrays ===> library => numpy 

# basic array creation

arr=np.array([1,2,3,4,5,9])
arr

array([1, 2, 3, 4, 5, 9])

In [3]:
a=[1,2,3,4,'hello']
np.array(a)

array(['1', '2', '3', '4', 'hello'], dtype='<U21')

In [4]:
# array generation function
arr=np.arange(1,11,2)
arr

array([1, 3, 5, 7, 9])

In [5]:
arr=np.zeros(6)
arr

array([0., 0., 0., 0., 0., 0.])

In [6]:
arr=np.zeros((4,8))
arr

array([[0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0.]])

In [7]:
arr=np.ones(6)
arr

array([1., 1., 1., 1., 1., 1.])

In [9]:
arr=np.ones((4,6))
arr

array([[1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.]])

In [11]:
arr=np.linspace(1,5,3)
arr

array([1., 3., 5.])

In [12]:
arr=np.linspace(1,5,10)
arr

array([1.        , 1.44444444, 1.88888889, 2.33333333, 2.77777778,
       3.22222222, 3.66666667, 4.11111111, 4.55555556, 5.        ])

In [13]:
# random generation function

np.random.rand(10)

array([0.63675015, 0.27824414, 0.97045339, 0.92724548, 0.90926843,
       0.58621757, 0.03654504, 0.40918916, 0.08247633, 0.31972071])

In [14]:
np.random.randn(10)

array([-1.45722863,  1.04205847,  0.85779634, -0.32590134,  0.78866057,
        0.65723362, -0.10479793,  0.24675275, -0.55756881,  0.70147573])

In [15]:
np.random.randint(10)

7

In [16]:
np.random.randint(10,20,10)

array([14, 17, 17, 19, 14, 11, 19, 12, 16, 10], dtype=int32)

In [17]:
# array attributes

arr=np.array([[1,2,3],[4,5,6],[7,8,9]])
arr.shape

(3, 3)

In [18]:
arr.size

9

In [19]:
arr.dtype

dtype('int64')

In [20]:
# array methods

arr.min()

np.int64(1)

In [21]:
arr.max()

np.int64(9)

In [22]:
arr.sum()

np.int64(45)

In [24]:
np.sum(arr,axis=0)
# column wise => axis=0 and row wise=> axis=1

array([12, 15, 18])

In [25]:
arr.argmax()

np.int64(8)

In [32]:
# reshaping and resizing

arr=np.arange(1,31)
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30])

In [33]:
arr=arr.reshape(6,5)

In [34]:
arr

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25],
       [26, 27, 28, 29, 30]])