In [19]:
import numpy as np

VALID SUDOKU

In [32]:
s = np.array([
    [5, 3, 4, 6, 7, 8, 9, 1, 2],
    [6, 7, 2, 1, 9, 5, 3, 4, 8],
    [1, 9, 8, 3, 4, 2, 5, 6, 7],

    [8, 5, 9, 7, 6, 1, 4, 2, 3],
    [4, 2, 6, 8, 5, 3, 7, 9, 1],
    [7, 1, 3, 9, 2, 4, 8, 5, 6],

    [9, 6, 1, 5, 3, 7, 2, 8, 4],
    [2, 8, 7, 4, 1, 9, 6, 3, 5],
    [3, 4, 5, 2, 8, 6, 1, 7, 9]
])

In [33]:
b=np.sum(s,axis=1)
b[b==45]

array([45, 45, 45, 45, 45, 45, 45, 45, 45])

In [34]:
b==45

array([ True,  True,  True,  True,  True,  True,  True,  True,  True])

In [35]:
for i in b:
    if i!=45:
        print("sudoku is not valid")
        break
else:
    print("rows => valid")

rows => valid


In [36]:
for i in range(0,9,3):
    for j in range(0,9,3):
        print(s[i:i+3,j:j+3])

[[5 3 4]
 [6 7 2]
 [1 9 8]]
[[6 7 8]
 [1 9 5]
 [3 4 2]]
[[9 1 2]
 [3 4 8]
 [5 6 7]]
[[8 5 9]
 [4 2 6]
 [7 1 3]]
[[7 6 1]
 [8 5 3]
 [9 2 4]]
[[4 2 3]
 [7 9 1]
 [8 5 6]]
[[9 6 1]
 [2 8 7]
 [3 4 5]]
[[5 3 7]
 [4 1 9]
 [2 8 6]]
[[2 8 4]
 [6 3 5]
 [1 7 9]]


In [37]:
for i in range(0, 9, 3):
    for j in range(0, 9, 3):
        n = s[i:i+3, j:j+3]
        print(n)
        print("Sum =", n.sum())
        print()

[[5 3 4]
 [6 7 2]
 [1 9 8]]
Sum = 45

[[6 7 8]
 [1 9 5]
 [3 4 2]]
Sum = 45

[[9 1 2]
 [3 4 8]
 [5 6 7]]
Sum = 45

[[8 5 9]
 [4 2 6]
 [7 1 3]]
Sum = 45

[[7 6 1]
 [8 5 3]
 [9 2 4]]
Sum = 45

[[4 2 3]
 [7 9 1]
 [8 5 6]]
Sum = 45

[[9 6 1]
 [2 8 7]
 [3 4 5]]
Sum = 45

[[5 3 7]
 [4 1 9]
 [2 8 6]]
Sum = 45

[[2 8 4]
 [6 3 5]
 [1 7 9]]
Sum = 45

