In [68]:
import numpy as np

VALID SUDOKU

In [69]:
s = np.array([
    [5, 3, 4, 6, 7, 8, 9, 1, 2],
    [6, 7, 2, 1, 9, 5, 3, 4, 8],
    [1, 9, 8, 3, 4, 2, 5, 6, 7],

    [8, 5, 9, 7, 6, 1, 4, 2, 3],
    [4, 2, 6, 8, 5, 3, 7, 9, 1],
    [7, 1, 3, 9, 2, 4, 8, 5, 6],

    [9, 6, 1, 5, 3, 7, 2, 8, 4],
    [2, 8, 7, 4, 1, 9, 6, 3, 5],
    [3, 4, 5, 2, 8, 6, 1, 7, 9]
])

In [70]:
b=np.sum(s,axis=1)
b[b==45]

array([45, 45, 45, 45, 45, 45, 45, 45, 45])

In [71]:
b==45

array([ True,  True,  True,  True,  True,  True,  True,  True,  True])

In [72]:
for i in b:
    if i!=45:
        print("sudoku is not valid")
        break
else:
    print("rows => valid")

rows => valid


In [73]:
for i in range(0,9,3):
    for j in range(0,9,3):
        print(s[i:i+3,j:j+3])

[[5 3 4]
 [6 7 2]
 [1 9 8]]
[[6 7 8]
 [1 9 5]
 [3 4 2]]
[[9 1 2]
 [3 4 8]
 [5 6 7]]
[[8 5 9]
 [4 2 6]
 [7 1 3]]
[[7 6 1]
 [8 5 3]
 [9 2 4]]
[[4 2 3]
 [7 9 1]
 [8 5 6]]
[[9 6 1]
 [2 8 7]
 [3 4 5]]
[[5 3 7]
 [4 1 9]
 [2 8 6]]
[[2 8 4]
 [6 3 5]
 [1 7 9]]


In [74]:
for i in range(0, 9, 3):
    for j in range(0, 9, 3):
        n = s[i:i+3, j:j+3]
        print(n)
        print("Sum =", n.sum())
        print()

[[5 3 4]
 [6 7 2]
 [1 9 8]]
Sum = 45

[[6 7 8]
 [1 9 5]
 [3 4 2]]
Sum = 45

[[9 1 2]
 [3 4 8]
 [5 6 7]]
Sum = 45

[[8 5 9]
 [4 2 6]
 [7 1 3]]
Sum = 45

[[7 6 1]
 [8 5 3]
 [9 2 4]]
Sum = 45

[[4 2 3]
 [7 9 1]
 [8 5 6]]
Sum = 45

[[9 6 1]
 [2 8 7]
 [3 4 5]]
Sum = 45

[[5 3 7]
 [4 1 9]
 [2 8 6]]
Sum = 45

[[2 8 4]
 [6 3 5]
 [1 7 9]]
Sum = 45



In [75]:
# general questions

# columns : [age, math marks, science marks ]

data=np.array([
    [18,85,78],
    [19,92,88],
    [17,76,95],
    [18,65,70],
    [20,90,85]]
    )

In [76]:
# get the shape of the matrix

data.shape

(5, 3)

In [77]:
# find the average age of the matrix
np.mean(data[:,0])

np.float64(18.4)

In [78]:
# extract math marks of all students

data[:,1:2]

array([[85],
       [92],
       [76],
       [65],
       [90]])

In [79]:
data[:,1]

array([85, 92, 76, 65, 90])

In [80]:
# find the highest science mark

np.max(data[:,2])

np.int64(95)

In [81]:
# get details of the student who scored more thn 90 in math.

data[:,1]>90

array([False,  True, False, False, False])

In [82]:
data[data[:,1]>90]

array([[19, 92, 88]])

In [83]:
# increase math marks of all students by 5

marks=data[:,1]+5
marks

array([90, 97, 81, 70, 95])

In [84]:
# find how many students are younger than 19

data[data[:,0]<19]

array([[18, 85, 78],
       [17, 76, 95],
       [18, 65, 70]])

In [85]:
# calculate the average marks in each subject ( column-wise mean )

np.mean(data[:,1:],axis=0)

array([81.6, 83.2])

In [86]:
# get data of students who scored at least 80 in both subjects

data[(data[:,1]>=80) & (data[:,2]>=80)]

array([[19, 92, 88],
       [20, 90, 85]])

In [87]:
# replace all science marks < 75 wih 0.

data[data[:,2]<75]=0
data

array([[18, 85, 78],
       [19, 92, 88],
       [17, 76, 95],
       [ 0,  0,  0],
       [20, 90, 85]])